# Generated by Django 3.0.5 on 2020-08-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=30)),
                ('STR', models.IntegerField(default=1)),
                ('DEX', models.IntegerField(default=1)),
                ('HEALTH', models.IntegerField(default=1)),
                ('INT', models.IntegerField(default=1)),
            ],
        ),
    ]
