# Generated by Django 3.0.5 on 2020-08-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chardata',
            name='bonusStat',
            field=models.IntegerField(default=0),
        ),
    ]
